port: 8080
circuit_breaker:
  thresholds:
    max_error_percentage: 70
    min_error_percentage: 10
  durations:
    state_interval: 10s
    closed_duration: 1m
  fallback:
    http_status: 200
    message: {"status":"11"}
statsd_host: http://localhost:8125
upstreams:
  /v1/test:
    host: "http://localhost:3000"
    add_error_conditions:
      response_body:
        path: status
        value: 11
  /v2:
    host: "http://localhost:3000"
    circuit_breaker_key:
      request_body_json_paths:
        - bank
